/*
 * Kathra Catalog Manager
 *
 * KATHRA Catalog Management API
 *
 * API version: 1.1.0-RC-SNAPSHOT
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	"os"

	"github.com/robfig/cron/v3"
	ws "gitlab.com/kathra/kathra/kathra-services/kathra-catalogmanager/kathra-catalogmanager-go/kathra-catalogmanager-helm/kathracatalogmanagerhelmservices"
)

func main() {
	log.Printf("Starting ...")

	var cronSettings = os.Getenv("HELM_UPDATE_INTERVAL")
	if cronSettings == "" {
		cronSettings = "* * * * *"
	}

	ws.HelmInitKathraRepository()

	log.Printf("Helm update ...")
	ws.HelmUpdate()

	log.Printf("Load all helm information in memory ...")
	ws.HelmLoadAllInMemory()

	cronScheduler := cron.New()
	cronScheduler.AddFunc(cronSettings, func() {
		log.Printf("Update Helm Chart..")
		ws.HelmUpdate()
		ws.HelmLoadAllInMemory()
	})
	cronScheduler.Start()

	log.Printf("Server started")

	router := ws.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
