/*
 * Kathra Catalog Manager
 *
 * KATHRA Catalog Management API
 *
 * API version: 1.1.0-RC-SNAPSHOT
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kathracatalogmanagerhelmservices

type HelmCatalogRepository struct {
	// Name
	Name string `json:"name,omitempty"`

	// Description
	Url string `json:"url,omitempty"`

	// Version
	Username string `json:"usernmae,omitempty"`

	// Uniq identifier
	Password string `json:"password,omitempty"`
}
