// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kathra-project/kathra-catalogmanager-helm/restapi/operations/read_catalog_entries"
)

// NewKathraCatalogmanagerHelmAPI creates a new KathraCatalogmanagerHelm instance
func NewKathraCatalogmanagerHelmAPI(spec *loads.Document) *KathraCatalogmanagerHelmAPI {
	return &KathraCatalogmanagerHelmAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		ReadCatalogEntriesGetAllCatalogEntryPackagesHandler: read_catalog_entries.GetAllCatalogEntryPackagesHandlerFunc(func(params read_catalog_entries.GetAllCatalogEntryPackagesParams) middleware.Responder {
			return middleware.NotImplemented("operation ReadCatalogEntriesGetAllCatalogEntryPackages has not yet been implemented")
		}),
		ReadCatalogEntriesGetCatalogEntryFromVersionHandler: read_catalog_entries.GetCatalogEntryFromVersionHandlerFunc(func(params read_catalog_entries.GetCatalogEntryFromVersionParams) middleware.Responder {
			return middleware.NotImplemented("operation ReadCatalogEntriesGetCatalogEntryFromVersion has not yet been implemented")
		}),
		ReadCatalogEntriesGetCatalogEntryPackageHandler: read_catalog_entries.GetCatalogEntryPackageHandlerFunc(func(params read_catalog_entries.GetCatalogEntryPackageParams) middleware.Responder {
			return middleware.NotImplemented("operation ReadCatalogEntriesGetCatalogEntryPackage has not yet been implemented")
		}),
		ReadCatalogEntriesGetCatalogEntryPackageVersionsHandler: read_catalog_entries.GetCatalogEntryPackageVersionsHandlerFunc(func(params read_catalog_entries.GetCatalogEntryPackageVersionsParams) middleware.Responder {
			return middleware.NotImplemented("operation ReadCatalogEntriesGetCatalogEntryPackageVersions has not yet been implemented")
		}),
	}
}

/*KathraCatalogmanagerHelmAPI KATHRA Catalog Management API permetting :
 * Generate source's packages from templates
 * Insert catalog entry from template

 * Insert catalog entry from file

 * Insert catalog entry from source repository
 * Read catalog entries from catalog
 */
type KathraCatalogmanagerHelmAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// ReadCatalogEntriesGetAllCatalogEntryPackagesHandler sets the operation handler for the get all catalog entry packages operation
	ReadCatalogEntriesGetAllCatalogEntryPackagesHandler read_catalog_entries.GetAllCatalogEntryPackagesHandler
	// ReadCatalogEntriesGetCatalogEntryFromVersionHandler sets the operation handler for the get catalog entry from version operation
	ReadCatalogEntriesGetCatalogEntryFromVersionHandler read_catalog_entries.GetCatalogEntryFromVersionHandler
	// ReadCatalogEntriesGetCatalogEntryPackageHandler sets the operation handler for the get catalog entry package operation
	ReadCatalogEntriesGetCatalogEntryPackageHandler read_catalog_entries.GetCatalogEntryPackageHandler
	// ReadCatalogEntriesGetCatalogEntryPackageVersionsHandler sets the operation handler for the get catalog entry package versions operation
	ReadCatalogEntriesGetCatalogEntryPackageVersionsHandler read_catalog_entries.GetCatalogEntryPackageVersionsHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *KathraCatalogmanagerHelmAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *KathraCatalogmanagerHelmAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *KathraCatalogmanagerHelmAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *KathraCatalogmanagerHelmAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *KathraCatalogmanagerHelmAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *KathraCatalogmanagerHelmAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *KathraCatalogmanagerHelmAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the KathraCatalogmanagerHelmAPI
func (o *KathraCatalogmanagerHelmAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ReadCatalogEntriesGetAllCatalogEntryPackagesHandler == nil {
		unregistered = append(unregistered, "read_catalog_entries.GetAllCatalogEntryPackagesHandler")
	}

	if o.ReadCatalogEntriesGetCatalogEntryFromVersionHandler == nil {
		unregistered = append(unregistered, "read_catalog_entries.GetCatalogEntryFromVersionHandler")
	}

	if o.ReadCatalogEntriesGetCatalogEntryPackageHandler == nil {
		unregistered = append(unregistered, "read_catalog_entries.GetCatalogEntryPackageHandler")
	}

	if o.ReadCatalogEntriesGetCatalogEntryPackageVersionsHandler == nil {
		unregistered = append(unregistered, "read_catalog_entries.GetCatalogEntryPackageVersionsHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *KathraCatalogmanagerHelmAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *KathraCatalogmanagerHelmAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *KathraCatalogmanagerHelmAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *KathraCatalogmanagerHelmAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *KathraCatalogmanagerHelmAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *KathraCatalogmanagerHelmAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the kathra catalogmanager helm API
func (o *KathraCatalogmanagerHelmAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *KathraCatalogmanagerHelmAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/catalogEntries"] = read_catalog_entries.NewGetAllCatalogEntryPackages(o.context, o.ReadCatalogEntriesGetAllCatalogEntryPackagesHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/catalogEntries/{providerId}/versions/{version}"] = read_catalog_entries.NewGetCatalogEntryFromVersion(o.context, o.ReadCatalogEntriesGetCatalogEntryFromVersionHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/catalogEntries/{providerId}"] = read_catalog_entries.NewGetCatalogEntryPackage(o.context, o.ReadCatalogEntriesGetCatalogEntryPackageHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/catalogEntries/{providerId}/versions"] = read_catalog_entries.NewGetCatalogEntryPackageVersions(o.context, o.ReadCatalogEntriesGetCatalogEntryPackageVersionsHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *KathraCatalogmanagerHelmAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *KathraCatalogmanagerHelmAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *KathraCatalogmanagerHelmAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *KathraCatalogmanagerHelmAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
