// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Kathra Catalog Manager
KATHRA Catalog Management API permetting :
 * Generate source's packages from templates
 * Insert catalog entry from template

 * Insert catalog entry from file

 * Insert catalog entry from source repository
 * Read catalog entries from catalog



    Schemes:
      http
    Host: localhost
    BasePath: /api/v1
    Version: 1.1.0-SNAPSHOT

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
