// Code generated by go-swagger; DO NOT EDIT.

package read_catalog_entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	CatalogEntryPackageVersion "github.com/kathra-project/kathra-core-model-go"
)

// GetCatalogEntryPackageOKCode is the HTTP code returned for type GetCatalogEntryPackageOK
const GetCatalogEntryPackageOKCode int = 200

/*GetCatalogEntryPackageOK CatalogEntryPackage with details

swagger:response getCatalogEntryPackageOK
*/
type GetCatalogEntryPackageOK struct {

	/*
	  In: Body
	*/
	Payload CatalogEntryPackageVersion.CatalogEntryPackageVersion `json:"body,omitempty"`
}

// NewGetCatalogEntryPackageOK creates GetCatalogEntryPackageOK with default headers values
func NewGetCatalogEntryPackageOK() *GetCatalogEntryPackageOK {

	return &GetCatalogEntryPackageOK{}
}

// WithPayload adds the payload to the get catalog entry package o k response
func (o *GetCatalogEntryPackageOK) WithPayload(payload CatalogEntryPackageVersion.CatalogEntryPackageVersion) *GetCatalogEntryPackageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get catalog entry package o k response
func (o *GetCatalogEntryPackageOK) SetPayload(payload CatalogEntryPackageVersion.CatalogEntryPackageVersion) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCatalogEntryPackageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
