// Code generated by go-swagger; DO NOT EDIT.

package read_catalog_entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCatalogEntryFromVersionHandlerFunc turns a function with the right signature into a get catalog entry from version handler
type GetCatalogEntryFromVersionHandlerFunc func(GetCatalogEntryFromVersionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCatalogEntryFromVersionHandlerFunc) Handle(params GetCatalogEntryFromVersionParams) middleware.Responder {
	return fn(params)
}

// GetCatalogEntryFromVersionHandler interface for that can handle valid get catalog entry from version params
type GetCatalogEntryFromVersionHandler interface {
	Handle(GetCatalogEntryFromVersionParams) middleware.Responder
}

// NewGetCatalogEntryFromVersion creates a new http.Handler for the get catalog entry from version operation
func NewGetCatalogEntryFromVersion(ctx *middleware.Context, handler GetCatalogEntryFromVersionHandler) *GetCatalogEntryFromVersion {
	return &GetCatalogEntryFromVersion{Context: ctx, Handler: handler}
}

/*GetCatalogEntryFromVersion swagger:route GET /catalogEntries/{providerId}/versions/{version} Read catalog entries getCatalogEntryFromVersion

Get an entry in the catalog for specific version

*/
type GetCatalogEntryFromVersion struct {
	Context *middleware.Context
	Handler GetCatalogEntryFromVersionHandler
}

func (o *GetCatalogEntryFromVersion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCatalogEntryFromVersionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
