swagger: "2.0"
info:
  description: "KATHRA Catalog Management API permetting : \n * Generate source's packages from templates \n * Insert catalog entry from template  \n \n * Insert catalog entry from file  \n\n * Insert catalog entry from source repository  \n * Read catalog entries from catalog \n "
  version: 1.3.0-SNAPSHOT
  title: Kathra Catalog Manager
  x-artifactName: catalogManager
  x-groupId: org.kathra
basePath: /api/v1
paths:
  /templates:
    get:
      tags:
        - Templating
      summary: Get all templates for catalog generation
      operationId: getTemplates
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: CatalogEntry wtih providerId
          schema:
            type: array
            items:
              $ref: '#/definitions/Template'
  /generateFromTemplate:
    post:
      tags:
        - Templating
      summary: Generate archive from template
      operationId: generateFromTemplate
      produces:
        - application/json
      parameters:
        - in: body
          name: Template
          description: CatalogEntry to create from Template
          required: true
          schema:
            $ref: '#/definitions/Template'
          x-exportParamName: Template
      responses:
        200:
          description: CatalogEntry wtih providerId
          schema:
            type: file
  /catalogEntries:
    get:
      tags:
        - Read catalog entries
      summary: Get all entries in the catalog
      operationId: getAllCatalogServices
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: CatalogEntry with providerId
          schema:
            type: array
            items:
              $ref: https://gitlab.com/kathra/kathra/kathra-core/kathra-core-api/raw/1.1.x/swagger.yml#/definitions/CatalogEntry
  /catalogEntries/{providerId}:
    get:
      tags:
        - Read catalog entries
      summary: Get an entry in the catalog
      operationId: getCatalogEntry
      produces:
        - application/json
      parameters:
        - name: providerId
          in: path
          description: CatalogEntry providerId
          required: true
          type: string
          x-exportParamName: ProviderId
      responses:
        200:
          description: CatalogEntry with details
          schema:
            $ref: https://gitlab.com/kathra/kathra/kathra-core/kathra-core-api/raw/1.1.x/swagger.yml#/definitions/CatalogEntry
  /catalogEntries/{providerId}/versions/{version}:
    get:
      tags:
        - Read catalog entries
      summary: Get an entry in the catalog for specific version
      operationId: getCatalogEntryFromVersion
      produces:
        - application/json
      parameters:
        - name: providerId
          in: path
          description: CatalogEntry providerId
          required: true
          type: string
          x-exportParamName: ProviderId
        - name: version
          in: path
          description: CatalogEntry version
          required: true
          type: string
          x-exportParamName: Version
      responses:
        200:
          description: CatalogEntry with details
          schema:
            $ref: https://gitlab.com/kathra/kathra/kathra-core/kathra-core-api/raw/1.1.x/swagger.yml#/definitions/CatalogEntry
  /catalogEntries/{providerId}/versions:
    get:
      tags:
        - Read catalog entries
      summary: Get all version for an entry in the catalog
      operationId: getCatalogEntryVersions
      produces:
        - application/json
      parameters:
        - name: providerId
          in: path
          description: CatalogEntry providerId
          required: true
          type: string
          x-exportParamName: ProviderId
      responses:
        200:
          description: All versions for CatalogEntry
          schema:
            $ref: https://gitlab.com/kathra/kathra/kathra-core/kathra-core-api/raw/1.1.x/swagger.yml#/definitions/CatalogEntry
  /catalogEntries/template:
    post:
      tags:
        - Add catalog entry
      summary: Create catalog entry from template
      operationId: addCatalogEntryFromTemplate
      produces:
        - application/json
      parameters:
        - in: body
          name: Template
          description: CatalogEntry to create from Template
          required: true
          schema:
            $ref: '#/definitions/Template'
          x-exportParamName: Template
      responses:
        200:
          description: Output type
          schema:
            $ref: https://gitlab.com/kathra/kathra/kathra-core/kathra-core-api/raw/1.1.x/swagger.yml#/definitions/CatalogEntry
  /catalogEntries/archive:
    post:
      tags:
        - Add catalog entry
      summary: Create catalog entry from archive file
      operationId: addCatalogEntryFromArchive
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: file
          in: formData
          description: The uploaded file data
          required: true
          type: file
          x-exportParamName: File
        - name: name
          in: path
          description: CatalogEntry's name
          required: true
          type: string
          x-exportParamName: Name
        - name: version
          in: path
          description: CatalogEntry's version
          required: true
          type: string
          x-exportParamName: Version
      responses:
        200:
          description: Output type
          schema:
            $ref: https://gitlab.com/kathra/kathra/kathra-core/kathra-core-api/raw/1.1.x/swagger.yml#/definitions/CatalogEntry
  /catalogEntries/sourceRepository:
    post:
      tags:
        - Add catalog entry
      summary: Create catalog entry from source repository's url
      operationId: addCatalogEntryFromSourceRepositoryUrl
      produces:
        - application/json
      parameters:
        - name: SourceRepositoryUrl
          in: query
          description: CatalogEntry to insert from source repository's URL
          required: true
          type: string
          x-exportParamName: SourceRepositoryUrl
        - name: branch
          in: path
          description: Source repository's branch/tag/commit
          required: true
          type: string
          x-exportParamName: Branch
        - name: name
          in: path
          description: CatalogEntry's name
          required: true
          type: string
          x-exportParamName: Name
        - name: version
          in: path
          description: CatalogEntry's version
          required: true
          type: string
          x-exportParamName: Version
      responses:
        200:
          description: Output type
          schema:
            $ref: https://gitlab.com/kathra/kathra/kathra-core/kathra-core-api/raw/1.1.x/swagger.yml#/definitions/CatalogEntry
definitions:
  Template:
    type: object
    properties:
      name:
        type: string
        description: Name
      arguments:
        type: array
        description: Catalog entry arguments
        items:
          $ref: '#/definitions/TemplateArgument'
    example:
      - name: RestApiService
        arguments:
          - key: CHART_NAME
            contrainst: '[A-Za-z0-9]'
          - key: CHART_VERSION
            contrainst: '[0-9]+\.[0-9]+\.[0-9]+'
          - key: CHART_DESCRIPTION
            contrainst: '[A-Za-z0-9]'
          - key: APP_VERSION
            contrainst: '[0-9]+\.[0-9]+\.[0-9]+'
          - key: IMAGE_NAME
            value: .+
          - key: IMAGE_TAG
            value: .+
          - key: REGISTRY_HOST
            value: .+
  TemplateArgument:
    type: object
    properties:
      key:
        type: string
        description: Argument key to generate catalog entry
      value:
        type: string
        description: Argument value to generate catalog entry
      contrainst:
        type: string
        description: Argument constraint
    example:
      contrainst: '[A-Za-z0-9]'
      value: MyFirstChart
      key: CHART_NAME
